name: Busted

on: [push, pull_request]

jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        lua_version: ["luajit-openresty", "luajit-2.1.0-beta3", "luajit-git"]
        os: ["ubuntu-latest"]
        include:
          - lua_version: "5.4.4"
            os: "windows-latest"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Setup ‘lua’
        uses: jkl1337/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua_version }}
      - name: Setup ‘luarocks’
        uses: jkl1337/gh-actions-luarocks@master
      - name: Setup dependencies
        run: |
          luarocks install busted
          luarocks install luacov-coveralls
      - name: Build C library
        run: |
          luarocks make --no-install
      - name: Run busted tests
        run: busted -c -v
      - name: Report test coverage
        if: success()
        continue-on-error: true
        run: luacov-coveralls -e .luarocks -e spec
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
